### ISSUE TITLE
Error backend "connection reset" and "request canceled" 

### ISSUE THREAD

**Issue by Stephen988** [crazy-max/docker-cloudflared#20]
Hi Crazymax I have recently installed your image on my raspberry pi 4 with docker but I have get two type of error:
- ERROR[2020-08-21T23:08:40Z] failed to connect to an HTTPS backend "https://1.1.1.1/dns-query": failed to perform an HTTPS request: Post https://1.1.1.1/dns-query: read tcp 192.168.178.50:**41594 (this two times with different port number 4xxxx)** ->1.1.1.1:443: read: connection reset by peer
and
- ERROR[2020-08-19T23:10:05Z] failed to connect to an HTTPS backend "https://1.1.1.1/dns-query": failed to perform an HTTPS request: Post https://1.1.1.1/dns-query: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

After restarting container work well but is a bit annoying.

**Comment by crazy-max** [comment]
@Stephen988 Looks like an upstream issue. See cloudflare/cloudflared#23 and cloudflare/cloudflared#91.

**Comment by MxD-js** [comment]
this has been resolved upstream. PR: https://github.com/cloudflare/cloudflared/pull/290

When can we pull the updated image with fixes applied?
