### ISSUE TITLE
High latency

### ISSUE THREAD

**Issue by simphide** [crazy-max/docker-cloudflared#22]
![image](https://user-images.githubusercontent.com/8183517/91894392-e71de600-ec95-11ea-9514-404ef95cfbd6.png)
> Latency

I am experiencing high latencies when I use the example docker compose file. Is this normal?

![image](https://user-images.githubusercontent.com/8183517/91894506-15032a80-ec96-11ea-874f-e1d15efc956b.png)
> Normal latency

My normal latency is between 25 and 50ms...

Thanks in advance

edit: the latency in the cloudflared docker container is much much better:

![image](https://user-images.githubusercontent.com/8183517/91897248-4b42a900-ec9a-11ea-9e09-99c54386e801.png)
> Container latency

```docker-compose.yml
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    hostname: home-server
    image: pihole/pihole:latest
    mac_address: '02:42:6a:57:70:bf'
    networks:
      pihole:
        ipv4_address: 172.21.0.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp"  # DHCP Server
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'XXX'
      DNS1: 172.21.0.3#5053
      DNS2: 172.21.0.3#5053
      ServerIP: 192.168.178.45
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
       #- './var-log/pihole.log:/var/log/pihole.log'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  cloudflared:
    image: crazymax/cloudflared:latest
    container_name: cloudflared
    hostname: cloudflared
    networks:
      pihole:
        ipv4_address: 172.21.0.3
    environment:
      TZ: 'Europe/Berlin'
      TUNNEL_DNS_UPSTREAM: 'https://1.1.1.1/dns-query,https://1.0.0.1/dns-query'
    restart: unless-stopped

networks:
  pihole:
    ipam:
      config:
        - subnet: 172.21.0.0/24
```

**Comment by crazy-max** [comment]
@simphide Can yo utry with the latest release?  (2020.10)

**Comment by simphide** [comment]
I downloaded the latest image, but the latencys remain the same... 

![image](https://user-images.githubusercontent.com/8183517/96229733-90dfda80-0f97-11eb-8fa5-ffbec4e854cc.png)

**Comment by crazy-max** [comment]
@simphide I have added a note about this. See https://github.com/crazy-max/docker-cloudflared#performance-issues
