### ISSUE TITLE
Health check fails

### ISSUE THREAD

**Issue by grandegiraffo** [crazy-max/docker-cloudflared#40]
### Behaviour

Cloudflared container runs normally but reports as unhealthy.

#### Steps to reproduce this issue

1. Pull my docker compose with your container https://github.com/grandegiraffo/pihole-doh
2. docker-compose up -d
3. Open Portainer or other tool to see health checks for all containers

#### Expected behaviour

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Configuration

* Docker version (type `docker --version`) : version 20.10.6, build 370c289
* Docker compose version if applicable (type `docker-compose --version`) : version 1.21.0
* Platform (Debian 9, Ubuntu 18.04, ...) : Raspbian 
* System info (type `uname -a`) : Linux 5.10.17-v8+ #1421 SMP PREEMPT Thu May 27 14:01:37 BST 2021 aarch64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
> Output of command `docker info`
```

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)
```

Status | unhealthy
Failure count | 21
Last output | time.c:126: Operation not permitted timer.c:634: fatal error: RUNTIME_CHECK(isc_time_now((&amp;now)) == 0) failed Aborted

**Comment by crazy-max** [comment]
@grandegiraffo What is the output of `docker info`?

**Comment by grandegiraffo** [comment]
```
pi@TastyPi:~ $ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.17-v8+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.706GiB
 Name: TastyPi
 ID: Z34J:PB2K:HS7S:PKDX:3C6X:5EE7:7JEV:R5IY:HV4J:JUKI:HIV3:FPNN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
```

**Comment by grandegiraffo** [comment]
Still failing health check on new crazymax/cloudflared:latest image (cdddccfc6ae9)

![A14B507D-0885-4A44-B774-A67D34F3DABC](https://user-images.githubusercontent.com/2128159/123505098-67ff0180-d65d-11eb-8bdd-c18388d0026e.jpeg)

**Comment by ValMati** [comment]
In my case the previous version didn't have any kind of problem, but the latest one does. The container reports unhealthy and seems to work correctly but not, if I check https://1.1.1.1/help it says I don't use DoH when with the previous version it said I did.

**Comment by poom** [comment]
Ref: https://github.com/visibilityspots/dockerfile-cloudflared/issues/30

**Comment by crazy-max** [comment]
I've made some changes in #41. Can you try with `crazymax/cloudflared:pr-41`?

**Comment by ValMati** [comment]
I've tried the version _pr-41_ and I have the same issue. Before appearing as unhealthy it is a long time starting. During this time in starting the logs do not change, the same messages appear from the beginning:
```
2021-06-29T18:33:46Z INF Starting metrics server on [::]:49312/metrics
2021-06-29T18:33:46Z INF Adding DNS upstream url=https://1.1.1.2/dns-query
2021-06-29T18:33:46Z INF Adding DNS upstream url=https://1.0.0.2/dns-query
2021-06-29T18:33:46Z INF Starting DNS over HTTPS proxy server address=dns://0.0.0.0:5053
``

**Comment by grandegiraffo** [comment]
I can't even use the `dig` command manually on the running container:
<img width="765" alt="Screenshot 2021-06-30 at 09 58 11" src="https://user-images.githubusercontent.com/2128159/123924001-d3acdb80-d989-11eb-9418-c3d5d3a389f6.png">

**Comment by poom** [comment]
I think the problem is alpine 3.13+ because this [tag/version](https://github.com/crazy-max/docker-cloudflared/tree/2021.4.0-r0)  working

**Comment by crazy-max** [comment]
Can't repro on

```
Linux server 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
```

or

```
Linux server 5.4.0-1032-raspi #35-Ubuntu SMP PREEMPT Fri Mar 19 20:52:40 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

Will dig into this issue. In the meantime you can disable the healthcheck:

```shell
docker run -d --no-healthcheck ...
```

```yaml
version: "3.5"

services:
  cloudflared:
    ...
    healthcheck:
      test: ["NONE"]
```

**Comment by poom** [comment]
I found the problem - It related [this article](https://docs.linuxserver.io/faq#libseccomp).

**Comment by ValMati** [comment]
> I found the problem - It related [this article](https://docs.linuxserver.io/faq#libseccomp).

This works for me. Thanks a lot!

**Comment by crazy-max** [comment]
@poom Thanks for your feedback.
