### ISSUE TITLE
Log Inspect via Docker CLI

### ISSUE THREAD

**Issue by corasaniti** [crazy-max/docker-cloudflared#49]
Hi just one information ...

I ran the container with Docker CLI (no docker-compose).  If I enter in docker container in ash console (via portainer) I would like to know where I find the logs.  
I would like to map logs across a volume with docker CLI and I was unable to find the path to the logs
Thanks

**Comment by crazy-max** [comment]
> If I enter in docker container in ash console (via portainer) I would like to know where I find the logs.

Logs are only available in standard output through `docker logs ...` or `docker compose logs`
